services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GitHub__User}
        NUGET_TECSUR_TOKEN: ${GitHub__NugetTecsurToken}
    container_name: tasacambio-worker
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Sbs__UrlXml=${Sbs__UrlXml}
      - Sbs__UrlHtml=${Sbs__UrlHtml}
      - Sbs__HoraInicioRegistro=${Sbs__HoraInicioRegistro}
      - Sbs__HoraFinRegistro=${Sbs__HoraFinRegistro}
      - Sbs__IntervaloBusquedaMinutos=${Sbs__IntervaloBusquedaMinutos}
      - Sbs__ValidacionPartesEnteras=${Sbs__ValidacionPartesEnteras}
      - Sbs__ValidacionPartesDecimales=${Sbs__ValidacionPartesDecimales}
      - Sbs__Monedas__0=${Sbs__Moneda0:-USD}
      - Sbs__Monedas__1=${Sbs__Monedas__1:-EUR}
      - ApiSettings__Infor__BaseUrl=${Infor__BaseUrl}
      - ApiSettings__Infor__SsoBaseUrl=${Infor__SsoBaseUrl}
      - ApiSettings__Infor__Tenant=${Infor__Tenant}
      - ApiSettings__Infor__ClientId=${Infor__ClientId}
      - ApiSettings__Infor__ClientSecret=${Infor__ClientSecret}
      - ApiSettings__Infor__ServiceAccountKey=${Infor__ServiceAccountKey}
      - ApiSettings__Infor__ServiceAccountSecret=${Infor__ServiceAccountSecret}
      - ApiSettings__Infor__AppId=${Infor__AppId}
      - ApiSettings__Infor__Configuration=${Infor__Configuration}
      - Serilog__SeqUrl=http://seq:5341
      - TZ=America/Lima
      - Loggings__Path=/app/logs
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: mysql:8.3
    container_name: tasacambio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${Mysql__RootPassword}
      MYSQL_DATABASE: ${Mysql__DataBase}
    ports:
      - "${Db__Port:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/sql/01_crear_base_datos.sql:/docker-entrypoint-initdb.d/01_crear_base_datos.sql:ro
      - ./scripts/sql/02_crear_tablas.sql:/docker-entrypoint-initdb.d/02_crear_tablas.sql:ro
      - ./scripts/sql/03_datos_iniciales.sql:/docker-entrypoint-initdb.d/03_datos_iniciales.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: tasacambio-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${Seq__AdminPassWord}
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data

volumes:
  mysql_data:
  seq_data:
